baseurl: /
markdown: rdiscount
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: http://www.barretlee.com/
demo: http://demo.barretlee.com/
base: http://snippets.barretlee.com
weibo: http://weibo.com/173248656
edit_path: https://github.com/barretlee/snippets/edit/gh-pages
new_path: https://github.com/barretlee/snippets/new/gh-pages/snippets
author: 小胡子哥
author_en: Barret Lee
email: barret.china@gmail.com
author_info: <a href="http://www.barretlee.com">小胡子哥</a>
